# For today's code challenge you will be reviewing yesterdays lecture material. Have fun!

### if you get done early check out [these videos](https://www.3blue1brown.com/neural-networks).

# The Perceptron

The first and simplest kind of neural network that we could talk about is the perceptron. A perceptron is just a single node or neuron of a neural network with nothing else. It can take any number of inputs and spit out an output. What a neuron does is it takes each of the input values, multplies each of them by a weight, sums all of these products up, and then passes the sum through what is called an "activation function" the result of which is the final value.

I really like figure 2.1 found in this [pdf](http://www.uta.fi/sis/tie/neuro/index/Neurocomputing2.pdf) even though it doesn't have bias term represented there.

![Figure 2.1](http://www.ryanleeallred.com/wp-content/uploads/2019/04/Screen-Shot-2019-04-01-at-2.34.58-AM.png)

If we were to write what is happening in some verbose mathematical notation, it might look something like this:

\begin{align}
 y = sigmoid(\sum(weight_{1}input_{1} + weight_{2}input_{2} + weight_{3}input_{3}) + bias)
\end{align}

Understanding what happens with a single neuron is important because this is the same pattern that will take place for all of our networks. 

When imagining a neural network I like to think about the arrows as representing the weights, like a wire that has a certain amount of resistance and only lets a certain amount of current through. And I like to think about the node itselef as containing the prescribed activation function that neuron will use to decide how much signal to pass onto the next layer.

# Activation Functions (transfer functions)

In Neural Networks, each node has an activation function. Each node in a given layer typically has the same activation function. These activation functions are the biggest piece of neural networks that have been inspired by actual biology. The activation function decides whether a cell "fires" or not. Sometimes it is said that the cell is "activated" or not. In Artificial Neural Networks activation functions decide how much signal to pass onto the next layer. This is why they are sometimes referred to as transfer functions because they determine how much signal is transferred to the next layer.

## Common Activation Functions:

![Activation Functions](http://www.snee.com/bobdc.blog/img/activationfunctions.png)

# Implementing a Perceptron from scratch in Python

### Establish training data

In [1]:
import numpy as np

np.random.seed(812)

inputs = np.array([
    [0, 0, 1],
    [1, 1, 1],
    [1, 0, 1],
    [0, 1, 1]
])

correct_outputs = [[0], [1], [1], [0]]

### Sigmoid activation function and its derivative for updating weights

In [2]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  sx = sigmoid(x)
  return sx * (1 - sx)

## Updating weights with derivative of sigmoid function:

![Sigmoid Function](https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Logistic-curve.svg/320px-Logistic-curve.svg.png)

### Initialize random weights for our three inputs

In [4]:
weights = 2 * np.random.random((inputs.shape[1], 1)) - 1
weights

array([[ 0.0099616 ],
       [ 0.21185521],
       [-0.08502562]])

### Calculate weighted sum of inputs and weights

In [6]:
bias = 2 * np.random.random((len(inputs), 1)) - 1

weighted_sum = np.dot(inputs, weights) + bias

weighted_sum

array([[0.82603536],
       [1.05458693],
       [0.39824372],
       [0.76535731]])

### Output the activated value for the end of 1 training epoch

In [9]:
activated_out = sigmoid(weighted_sum)
activated_out

array([[0.69551598],
       [0.74165474],
       [0.59826562],
       [0.68251573]])

### take difference of output and true values to calculate error

In [10]:
error = correct_outputs - activated_out
adjust = error * sigmoid_derivative(activated_out)

### Put it all together

In [11]:
bias += error
weights += np.dot(inputs.T, adjust)

In [12]:
weights

array([[ 0.15837836],
       [ 0.11611031],
       [-0.24325056]])

In [13]:
activated_out

array([[0.69551598],
       [0.74165474],
       [0.59826562],
       [0.68251573]])

In [ ]:
for i in range(10000):
    